INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (1,1,'A00','A09','Doenças infecciosas intestinais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (2,1,'A15','A19','Tuberculose');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (3,1,'A20','A28','Algumas doenças bacterianas zoonóticas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (4,1,'A30','A49','Outras doenças bacterianas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (5,1,'A50','A64','Infecções de transmissão predominantemente sexual');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (6,1,'A65','A69','Outras doenças por espiroquetas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (7,1,'A70','A74','Outras doenças causadas por clamídias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (8,1,'A75','A79','Rickettsioses');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (9,1,'A80','A89','Infecções virais do sistema nervoso central');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (10,1,'A90','A99','Febres por arbovírus e febres hemorrágicas virais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (11,1,'B00','B09','Infecções virais caracterizadas por lesões de pele e mucosas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (12,1,'B15','B19','Hepatite viral');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (13,1,'B20','B24','Doença pelo vírus da imunodeficiência humana [HIV]');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (14,1,'B25','B34','Outras doenças por vírus');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (15,1,'B35','B49','Micoses');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (16,1,'B50','B64','Doenças devidas a protozoários');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (17,1,'B65','B83','Helmintíases');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (18,1,'B85','B89','Pediculose');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (19,1,'B90','B94','Seqüelas de doenças infecciosas e parasitárias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (20,1,'B95','B97','Agentes de infecções bacterianas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (21,1,'B99','B99','Outras doenças infecciosas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (22,2,'C00','C97','Neoplasias [tumores] malignas(os)');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (23,2,'C00','C75','Neoplasias [tumores] malignas(os)');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (24,2,'C00','C14','Neoplasias malignas do lábio');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (25,2,'C15','C26','Neoplasias malignas dos órgãos digestivos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (26,2,'C30','C39','Neoplasias malignas do aparelho respiratório e dos órgãos intratorácicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (27,2,'C40','C41','Neoplasias malignas dos ossos e das cartilagens articulares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (28,2,'C43','C44','Melanoma e outras(os) neoplasias malignas da pele');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (29,2,'C45','C49','Neoplasias malignas do tecido mesotelial e tecidos moles');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (30,2,'C50','C50','Neoplasias malignas da mama');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (31,2,'C51','C58','Neoplasias malignas dos órgãos genitais femininos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (32,2,'C60','C63','Neoplasias malignas dos órgãos genitais masculinos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (33,2,'C64','C68','Neoplasias malignas do trato urinário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (34,2,'C69','C72','Neoplasias malignas dos olhos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (35,2,'C73','C75','Neoplasias malignas da tireóide e de outras glândulas endócrinas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (36,2,'C76','C80','Neoplasias malignas de localizações mal definidas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (37,2,'C81','C96','Neoplasias [tumores] malignas(os)');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (38,2,'C97','C97','Neoplasias malignas de localizações múltiplas independentes (primárias)');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (39,2,'D00','D09','Neoplasias [tumores] in situ');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (40,2,'D10','D36','Neoplasias [tumores] benignas(os)');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (41,2,'D37','D48','Neoplasias [tumores] de comportamento incerto ou desconhecido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (42,3,'D50','D53','Anemias nutricionais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (43,3,'D55','D59','Anemias hemolíticas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (44,3,'D60','D64','Anemias aplásticas e outras anemias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (45,3,'D65','D69','Defeitos da coagulação');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (46,3,'D70','D77','Outras doenças do sangue e dos órgãos hematopoéticos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (47,3,'D80','D89','Alguns transtornos que comprometem o mecanismo imunitário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (48,4,'E00','E07','Transtornos da glândula tireóide');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (49,4,'E10','E14','Diabetes mellitus');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (50,4,'E15','E16','Outros transtornos da regulação da glicose e da secreção pancreática interna');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (51,4,'E20','E35','Transtornos de outras glândulas endócrinas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (52,4,'E40','E46','Desnutrição');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (53,4,'E50','E64','Outras deficiências nutricionais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (54,4,'E65','E68','Obesidade e outras formas de hiperalimentação');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (55,4,'E70','E90','Distúrbios metabólicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (56,5,'F00','F09','Transtornos mentais orgânicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (57,5,'F10','F19','Transtornos mentais e comportamentais devidos ao uso de substância psicoativa');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (58,5,'F20','F29','Esquizofrenia');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (59,5,'F30','F39','Transtornos do humor [afetivos]');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (60,5,'F40','F48','Transtornos neuróticos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (61,5,'F50','F59','Síndromes comportamentais associadas a disfunções fisiológicas e a fatores físicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (62,5,'F60','F69','Transtornos da personalidade e do comportamento do adulto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (63,5,'F70','F79','Retardo mental');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (64,5,'F80','F89','Transtornos do desenvolvimento psicológico');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (65,5,'F90','F98','Transtornos do comportamento e transtornos emocionais que aparecem habitualmente durante a infância ou a adolescência');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (66,5,'F99','F99','Transtorno mental não especificado');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (67,6,'G00','G09','Doenças inflamatórias do sistema nervoso central');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (68,6,'G10','G13','Atrofias sistêmicas que afetam principalmente o sistema nervoso central');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (69,6,'G20','G26','Doenças extrapiramidais e transtornos dos movimentos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (70,6,'G30','G32','Outras doenças degenerativas do sistema nervoso');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (71,6,'G35','G37','Doenças desmielinizantes do sistema nervoso central');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (72,6,'G40','G47','Transtornos episódicos e paroxísticos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (73,6,'G50','G59','Transtornos dos nervos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (74,6,'G60','G64','Polineuropatias e outros transtornos do sistema nervoso periférico');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (75,6,'G70','G73','Doenças da junção mioneural e dos músculos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (76,6,'G80','G83','Paralisia cerebral e outras síndromes paralíticas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (77,6,'G90','G99','Outros transtornos do sistema nervoso');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (78,7,'H00','H06','Transtornos da pálpebra');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (79,7,'H10','H13','Transtornos da conjuntiva');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (80,7,'H15','H22','Transtornos da esclerótica');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (81,7,'H25','H28','Transtornos do cristalino');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (82,7,'H30','H36','Transtornos da coróide e da retina');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (83,7,'H40','H42','Glaucoma');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (84,7,'H43','H45','Transtornos do humor vítreo e do globo ocular');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (85,7,'H46','H48','Transtornos do nervo óptico e das vias ópticas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (86,7,'H49','H52','Transtornos dos músculos oculares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (87,7,'H53','H54','Transtornos visuais e cegueira');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (88,7,'H55','H59','Outros transtornos do olho e anexos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (89,8,'H60','H62','Doenças do ouvido externo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (90,8,'H65','H75','Doenças do ouvido médio e da mastóide');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (91,8,'H80','H83','Doenças do ouvido interno');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (92,8,'H90','H95','Outros transtornos do ouvido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (93,9,'I00','I02','Febre reumática aguda');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (94,9,'I05','I09','Doenças reumáticas crônicas do coração');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (95,9,'I10','I15','Doenças hipertensivas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (96,9,'I20','I25','Doenças isquêmicas do coração');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (97,9,'I26','I28','Doenças cardíaca pulmonar e da circulação pulmonar');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (98,9,'I30','I52','Outras formas de doença do coração');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (99,9,'I60','I69','Doenças cerebrovasculares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (100,9,'I70','I79','Doenças das artérias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (101,9,'I80','I89','Doenças das veias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (102,9,'I95','I99','Outros transtornos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (103,10,'J00','J06','Infecções agudas das vias aéreas superiores');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (104,10,'J09','J18','Influenza [gripe] e pneumonia');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (105,10,'J20','J22','Outras infecções agudas das vias aéreas inferiores');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (106,10,'J30','J39','Outras doenças das vias aéreas superiores');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (107,10,'J40','J47','Doenças crônicas das vias aéreas inferiores');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (108,10,'J60','J70','Doenças pulmonares devidas a agentes externos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (109,10,'J80','J84','Outras doenças respiratórias que afetam principalmente o interstício');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (110,10,'J85','J86','Afecções necróticas e supurativas das vias aéreas inferiores');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (111,10,'J90','J94','Outras doenças da pleura');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (112,10,'J95','J99','Outras doenças do aparelho respiratório');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (113,11,'K00','K14','Doenças da cavidade oral');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (114,11,'K20','K31','Doenças do esôfago');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (115,11,'K35','K38','Doenças do apêndice');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (116,11,'K40','K46','Hérnias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (117,11,'K50','K52','Enterites e colites não-infecciosas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (118,11,'K55','K63','Outras doenças dos intestinos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (119,11,'K65','K67','Doenças do peritônio');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (120,11,'K70','K77','Doenças do fígado');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (121,11,'K80','K87','Transtornos da vesícula biliar');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (122,11,'K90','K93','Outras doenças do aparelho digestivo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (123,12,'L00','L08','Infecções da pele e do tecido subcutâneo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (124,12,'L10','L14','Afecções bolhosas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (125,12,'L20','L30','Dermatite e eczema');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (126,12,'L40','L45','Afecções pápulo-descamativas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (127,12,'L50','L54','Urticária e eritema');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (128,12,'L55','L59','Transtornos da pele e do tecido subcutâneo relacionados com a radiação');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (129,12,'L60','L75','Afecções dos anexos da pele');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (130,12,'L80','L99','Outras afecções da pele e do tecido subcutâneo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (131,13,'M00','M25','Artropatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (132,13,'M00','M03','Artropatias infecciosas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (133,13,'M05','M14','Poliartropatias inflamatórias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (134,13,'M15','M19','Artroses');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (135,13,'M20','M25','Outros transtornos articulares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (136,13,'M30','M36','Doenças sistêmicas do tecido conjuntivo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (137,13,'M40','M54','Dorsopatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (138,13,'M40','M43','Dorsopatias deformantes');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (139,13,'M45','M49','Espondilopatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (140,13,'M50','M54','Outras dorsopatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (141,13,'M60','M79','Transtornos dos tecidos moles');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (142,13,'M60','M63','Transtornos musculares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (143,13,'M65','M68','Transtornos das sinóvias e dos tendões');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (144,13,'M70','M79','Outros transtornos dos tecidos moles');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (145,13,'M80','M94','Osteopatias e condropatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (146,13,'M80','M85','Transtornos da densidade e da estrutura óssea');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (147,13,'M86','M90','Outras osteopatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (148,13,'M91','M94','Condropatias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (149,13,'M95','M99','Outros transtornos do sistema osteomuscular e do tecido conjuntivo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (150,14,'N00','N08','Doenças glomerulares');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (151,14,'N10','N16','Doenças renais túbulo-intersticiais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (152,14,'N17','N19','Insuficiência renal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (153,14,'N20','N23','Calculose renal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (154,14,'N25','N29','Outros transtornos do rim e do ureter');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (155,14,'N30','N39','Outras doenças do aparelho urinário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (156,14,'N40','N51','Doenças dos órgãos genitais masculinos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (157,14,'N60','N64','Doenças da mama');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (158,14,'N70','N77','Doenças inflamatórias dos órgãos pélvicos femininos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (159,14,'N80','N98','Transtornos não-inflamatórios do trato genital feminino');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (160,14,'N99','N99','Outros transtornos do aparelho geniturinário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (161,15,'O00','O08','Gravidez que termina em aborto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (162,15,'O10','O16','Edema');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (163,15,'O20','O29','Outros transtornos maternos relacionados predominantemente com a gravidez');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (164,15,'O30','O48','Assistência prestada à mãe por motivos ligados ao feto e à cavidade amniótica e por possíveis problemas relativos ao parto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (165,15,'O60','O75','Complicações do trabalho de parto e do parto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (166,15,'O80','O84','Parto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (167,15,'O85','O92','Complicações relacionadas predominantemente com o puerpério');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (168,15,'O94','O99','Outras afecções obstétricas não classificadas em outra parte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (169,16,'P00','P04','Feto e recém-nascido afetados por fatores maternos e por complicações da gravidez');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (170,16,'P05','P08','Transtornos relacionados com a duração da gestação e com o crescimento fetal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (171,16,'P10','P15','Traumatismo de parto');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (172,16,'P20','P29','Transtornos respiratórios e cardiovasculares específicos do período perinatal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (173,16,'P35','P39','Infecções específicas do período perinatal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (174,16,'P50','P61','Transtornos hemorrágicos e hematológicos do feto e do recém-nascido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (175,16,'P70','P74','Transtornos endócrinos e metabólicos transitórios específicos do feto e do recém-nascido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (176,16,'P75','P78','Transtornos do aparelho digestivo do feto ou do recém-nascido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (177,16,'P80','P83','Afecções comprometendo o tegumento e a regulação térmica do feto e do recém-nascido');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (178,16,'P90','P96','Outros transtornos originados no período perinatal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (179,17,'Q00','Q07','Malformações congênitas do sistema nervoso');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (180,17,'Q10','Q18','Malformações congênitas do olho');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (181,17,'Q20','Q28','Malformações congênitas do aparelho circulatório');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (182,17,'Q30','Q34','Malformações congênitas do aparelho respiratório');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (183,17,'Q35','Q37','Fenda labial e fenda palatina');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (184,17,'Q38','Q45','Outras malformações congênitas do aparelho digestivo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (185,17,'Q50','Q56','Malformações congênitas dos órgãos genitais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (186,17,'Q60','Q64','Malformações congênitas do aparelho urinário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (187,17,'Q65','Q79','Malformações e deformidades congênitas do sistema osteomuscular');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (188,17,'Q80','Q89','Outras malformações congênitas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (189,17,'Q90','Q99','Anomalias cromossômicas não classificadas em outra parte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (190,18,'R00','R09','Sintomas e sinais relativos ao aparelho circulatório e respiratório');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (191,18,'R10','R19','Sintomas e sinais relativos ao aparelho digestivo e ao abdome');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (192,18,'R20','R23','Sintomas e sinais relativos à pele e ao tecido subcutâneo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (193,18,'R25','R29','Sintomas e sinais relativos aos sistemas nervoso e osteomuscular');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (194,18,'R30','R39','Sintomas e sinais relativos ao aparelho urinário');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (195,18,'R40','R46','Sintomas e sinais relativos à cognição');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (196,18,'R47','R49','Sintomas e sinais relativos à fala e à voz');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (197,18,'R50','R69','Sintomas e sinais gerais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (198,18,'R70','R79','Achados anormais de exames de sangue');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (199,18,'R80','R82','Achados anormais de exames de urina');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (200,18,'R83','R89','Achados anormais de exames e de outros líquidos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (201,18,'R90','R94','Achados anormais de exames para diagnóstico por imagem e em estudos de função');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (202,18,'R95','R99','Causas mal definidas e desconhecidas de mortalidade');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (203,19,'S00','S09','Traumatismos da cabeça');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (204,19,'S10','S19','Traumatismos do pescoço');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (205,19,'S20','S29','Traumatismos do tórax');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (206,19,'S30','S39','Traumatismos do abdome');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (207,19,'S40','S49','Traumatismos do ombro e do braço');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (208,19,'S50','S59','Traumatismos do cotovelo e do antebraço');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (209,19,'S60','S69','Traumatismos do punho e da mão');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (210,19,'S70','S79','Traumatismos do quadril e da coxa');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (211,19,'S80','S89','Traumatismos do joelho e da perna');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (212,19,'S90','S99','Traumatismos do tornozelo e do pé');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (213,19,'T00','T07','Traumatismos envolvendo múltiplas regiões do corpo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (214,19,'T08','T14','Traumatismos de localização não especificada do tronco');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (215,19,'T15','T19','Efeito da penetração de corpo estranho através de orifício natural');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (216,19,'T20','T32','Queimaduras e corrosões');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (217,19,'T20','T25','Queimaduras e corrosões da superfície externa do corpo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (218,19,'T26','T28','Queimaduras e corrosões limitadas ao olho e aos órgãos internos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (219,19,'T29','T32','Queimaduras e corrosões de múltiplas regiões e de regiões não especificadas do corpo');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (220,19,'T33','T35','Geladuras [frostbite]');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (221,19,'T36','T50','Intoxicação por drogas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (222,19,'T51','T65','Efeitos tóxicos de substâncias de origem predominantemente não-medicinal');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (223,19,'T66','T78','Outros efeitos de causas externas e os não especificados');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (224,19,'T79','T79','Algumas complicações precoces de traumatismos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (225,19,'T80','T88','Complicações de cuidados médicos e cirúrgicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (226,19,'T90','T98','Seqüelas de traumatismos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (227,20,'V01','X59','Acidentes');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (228,20,'V01','V99','Acidentes de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (229,20,'V01','V09','Pedestre traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (230,20,'V10','V19','Ciclista traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (231,20,'V20','V29','Motociclista traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (232,20,'V30','V39','Ocupante de triciclo motorizado traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (233,20,'V40','V49','Ocupante de um automóvel traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (234,20,'V50','V59','Ocupante de uma caminhonete traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (235,20,'V60','V69','Ocupante de um veículo de transporte pesado traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (236,20,'V70','V79','Ocupante de um ônibus traumatizado em um acidente de transporte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (237,20,'V80','V89','Outros acidentes de transporte terrestre');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (238,20,'V90','V94','Acidentes de transporte por água');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (239,20,'V95','V97','Acidentes de transporte aéreo e espacial');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (240,20,'V98','V99','Outros acidentes de transporte e os não especificados');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (241,20,'W00','X59','Outras causas externas de traumatismos acidentais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (242,20,'W00','W19','Quedas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (243,20,'W20','W49','Exposição a forças mecânicas inanimadas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (244,20,'W50','W64','Exposição a forças mecânicas animadas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (245,20,'W65','W74','Afogamento e submersão acidentais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (246,20,'W75','W84','Outros riscos acidentais à respiração');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (247,20,'W85','W99','Exposição à corrente elétrica');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (248,20,'X00','X09','Exposição à fumaça');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (249,20,'X10','X19','Contato com uma fonte de calor ou com substâncias quentes');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (250,20,'X20','X29','Contato com animais e plantas venenosos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (251,20,'X30','X39','Exposição às forças da natureza');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (252,20,'X40','X49','Envenenamento [intoxicação] acidental por e exposição à substâncias nocivas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (253,20,'X50','X57','Excesso de esforços');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (254,20,'X58','X59','Exposição acidental a outros fatores e aos não especificados');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (255,20,'X60','X84','Lesões autoprovocadas intencionalmente');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (256,20,'X85','Y09','Agressões');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (257,20,'Y10','Y34','Eventos (fatos) cuja intenção é indeterminada');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (258,20,'Y35','Y36','Intervenções legais e operações de guerra');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (259,20,'Y40','Y84','Complicações de assistência médica e cirúrgica');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (260,20,'Y40','Y59','Efeitos adversos de drogas');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (261,20,'Y60','Y69','Acidentes ocorridos em pacientes durante a prestação de cuidados médicos e cirúrgicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (262,20,'Y70','Y82','Incidentes adversos durante atos diagnósticos ou terapêuticos associados ao uso de dispositivos (aparelhos) médicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (263,20,'Y83','Y84','Reação anormal em paciente ou complicação tardia causadas por procedimentos cirúrgicos e outros procedimentos médicos sem menção de acidente ao tempo do procedimento');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (264,20,'Y85','Y89','Seqüelas de causas externas de morbidade e de mortalidade');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (265,20,'Y90','Y98','Fatores suplementares relacionados com as causas de morbidade e de mortalidade classificados em outra parte');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (266,21,'Z00','Z13','Pessoas em contato com os serviços de saúde para exame e investigação');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (267,21,'Z20','Z29','Pessoas com riscos potenciais à saúde relacionados com doenças transmissíveis');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (268,21,'Z30','Z39','Pessoas em contato com os serviços de saúde em circunstâncias relacionadas com a reprodução');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (269,21,'Z40','Z54','Pessoas em contato com os serviços de saúde para procedimentos e cuidados específicos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (270,21,'Z55','Z65','Pessoas com riscos potenciais à saúde relacionados com circunstâncias socioeconômicas e psicossociais');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (271,21,'Z70','Z76','Pessoas em contato com os serviços de saúde em outras circunstâncias');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (272,21,'Z80','Z99','Pessoas com riscos potenciais à saúde relacionados com história familiar e pessoal e algumas afecções que influenciam o estado de saúde');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (273,22,'U04','U04','Designação provisória de novas doenças de etiologia incerta');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (274,22,'U80','U89','Agentes bacterianos resistentes a antibióticos');
INSERT INTO cid_grupo(id,capitulo_id,cat_inicio,cat_fim,descricao) VALUES (275,22,'U99','U99','CID 10ª Revisão não disponível');
